name: Deploy master branch

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  job_id:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.gcp_credentials }}'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: 'dogs'
        runtime: 'nodejs16'
        
